# Generated by Django 3.0.4 on 2020-05-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='discription',
            new_name='description',
        ),
    ]
